/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TrackpadDevice {
  id: bigint
  isBuiltin: boolean
}
export declare function isSupported(): boolean
export declare function listDevices(): Array<TrackpadDevice>
export declare function actuateWithDeviceId(deviceId: bigint, actuationId: number, intensity: number): void
export declare function actuate(actuationId: number, intensity: number): void
export declare function click(): void
export declare function weakClick(): void
export declare function strongClick(): void
